//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace girisform
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class librayautomationEntities : DbContext
    {
        public librayautomationEntities()
            : base("name=librayautomationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblbooks> tblbooks { get; set; }
        public virtual DbSet<tblborrowedbooks> tblborrowedbooks { get; set; }
        public virtual DbSet<tblcategories> tblcategories { get; set; }
        public virtual DbSet<tblmembers> tblmembers { get; set; }
        public virtual DbSet<tbladminup> tbladminup { get; set; }
    }
}
