//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace girisform
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbladminup
    {
        public int kullaniciid { get; set; }
        public string kullaniciadi { get; set; }
        public string sifre { get; set; }
    }
}
