//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace girisform
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblborrowedbooks
    {
        public int emanetid { get; set; }
        public Nullable<int> kitapid { get; set; }
        public Nullable<int> uyeid { get; set; }
        public Nullable<System.DateTime> alistarihi { get; set; }
        public Nullable<System.DateTime> iadetarihi { get; set; }
        public string iadedurumu { get; set; }
    
        public virtual tblbooks tblbooks { get; set; }
        public virtual tblmembers tblmembers { get; set; }
    }
}
