//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace girisform
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbooks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblbooks()
        {
            this.tblborrowedbooks = new HashSet<tblborrowedbooks>();
        }
    
        public int kitapid { get; set; }
        public string kitapismi { get; set; }
        public string yazar { get; set; }
        public string yayinevi { get; set; }
        public string sayfasayisi { get; set; }
        public string kategori { get; set; }
        public Nullable<int> stok { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblborrowedbooks> tblborrowedbooks { get; set; }
    }
}
