//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace girisform
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmembers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblmembers()
        {
            this.tblborrowedbooks = new HashSet<tblborrowedbooks>();
        }
    
        public int uyeid { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string telno { get; set; }
        public string email { get; set; }
        public string adres { get; set; }
        public System.DateTime kayittarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblborrowedbooks> tblborrowedbooks { get; set; }
    }
}
